# Generated by Django 5.2.7 on 2025-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы, к которым принадлежит пользователь..",
                related_name="customuser_set",
                to="auth.group",
                verbose_name="группы",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Специфические разрешения для пользователя.",
                related_name="customuser_set",
                to="auth.permission",
                verbose_name="права пользователя",
            ),
        ),
    ]
