[project]
name = "coursework-5"
version = "0.1.0"
description = ""
authors = [
    {name = "Dmitri_Sidorov",email = "kin19861@rambler.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
