# Generated by Django 5.2.7 on 2025-10-22 19:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=30, verbose_name="место привычки")),
                ("start_time", models.TimeField(verbose_name="время начала выполнения привычки")),
                ("action", models.CharField(verbose_name="действие привычки")),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name="периодичность"),
                ),
                ("reward", models.CharField(blank=True, max_length=50, null=True, verbose_name="вознаграждение")),
                (
                    "time_to_complete",
                    models.TimeField(
                        validators=[django.core.validators.MaxValueValidator(datetime.time(0, 2))],
                        verbose_name="время для выполнения привычки",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habits",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
